extends Control
@onready var coins: Label = $VBoxContainer/HBoxContainer/MarginContainer3/coins
@onready var time: Label = $VBoxContainer/HBoxContainer/MarginContainer2/VBoxContainer/time
@onready var time_progress: ProgressBar = $VBoxContainer/HBoxContainer/MarginContainer2/VBoxContainer/timeProgress
@onready var health: Label = $VBoxContainer/HBoxContainer/MarginContainer/VBoxContainer/health
@onready var health_progress: ProgressBar = $VBoxContainer/HBoxContainer/MarginContainer/VBoxContainer/healthProgress


# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	health.text="HEALTH"
	time.text="00:00"
	coins.text = "COINS - 0"

func healthUpdate(currentHealth, maxHealth):
	health.text = "HEALTH "+str(currentHealth)
	health_progress.value = float(currentHealth) / maxHealth * 100
	
func timeUpdate(timeRemaining, timeAvailable):
	time.text = "TIME "+str(timeRemaining)+" of "+str(timeAvailable)
	time_progress.value = float(timeRemaining) / timeAvailable * 100
	
func coinsUpdate(collected, available):
	coins.text="COINS "+str(collected)+" of "+str(available)
